name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  release:
    types: [ created ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Create Build Environment
      run: |
        curl -L -o /tmp/wasi.deb https://github.com/WebAssembly/wasi-sdk/releases/download/wasi-sdk-12/wasi-sdk_12.0_amd64.deb
        sudo dpkg -i /tmp/wasi.deb
        rm /tmp/wasi.deb

    - name: Cache Build
      id: cache-build
      uses: actions/cache@v2
      with:
        path: build
        key: ubuntu-latest

    - name: Build
      run: make

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: libquirc.wasm
        path: libquirc.wasm

    - name: Get Release Upload URL
      if: github.event_name == 'release'
      id: get_release
      uses: bruceadams/get-release@v1.2.2
      env:
        GITHUB_TOKEN: ${{github.token}}

    - name: Upload Release Asset (Standalone)
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1.0.2
      env:
        GITHUB_TOKEN: ${{github.token}}
      with:
        upload_url: ${{steps.get_release.outputs.upload_url}}
        asset_path: libquirc.wasm
        asset_name: libquirc.wasm
        asset_content_type: application/wasm
